### 3.3 Manejo y operaciones con cadenas en Python

En Python, las **cadenas de texto (strings)** son una secuencia de caracteres que se escriben entre comillas simples `' '` o dobles `" "`.

#### 1. Creación de cadenas
```python
texto1 = "Hola"
texto2 = 'Mundo'


2. Concatenación (unir cadenas)

Se utiliza el operador + para unir dos o más cadenas.

In [ ]:
saludo = "Hola" + " " + "Mundo"
print(saludo)  # Hola Mundo


3. Repetición

El operador * permite repetir una cadena varias veces.

In [2]:
eco = "Python " * 3
print(eco)  # Python Python Python


Python Python Python 


4. Indexación

Se pueden acceder a los caracteres de una cadena usando índices (inician en 0).

In [1]:
palabra = "Python"
print(palabra[0])  # P
print(palabra[-1]) # n


P
n


5. Slicing (rebanado)

Permite obtener subcadenas indicando posiciones inicial y final.

In [3]:
palabra = "Programación"
print(palabra[0:7])   # Program
print(palabra[5:])    # amación
print(palabra[:5])    # Progr
print(palabra[2:6])  

Program
amación
Progr
ogra


6. Funciones y métodos comunes con cadenas

len(cadena) → devuelve la longitud de la cadena.

cadena.upper() → convierte a mayúsculas.

cadena.lower() → convierte a minúsculas.

cadena.title() → convierte la primera letra de cada palabra en mayúscula.

cadena.strip() → elimina espacios en blanco al inicio y final.

cadena.replace("a", "o") → reemplaza caracteres.

cadena.split(" ") → separa la cadena en una lista.

"separador".join(lista) → une elementos de una lista en una sola cadena.



In [5]:
texto = "  Python es divertido  "

# Longitud
print(len(texto))

# Quitar espacios extras
print(texto.strip())

# Mayúsculas y minúsculas
print(texto.upper())
print(texto.lower())

# Reemplazar palabras
print(texto.replace("divertido", "poderoso"))

# Dividir en palabras
palabras = texto.split()
print(palabras)

# Unir palabras con guiones
nuevo = " ".join(palabras)
print(nuevo)



23
Python es divertido
  PYTHON ES DIVERTIDO  
  python es divertido  
  Python es poderoso  
['Python', 'es', 'divertido']
Python es divertido


7. Verificación

cadena.startswith("texto") → verifica si empieza con algo.

cadena.endswith("texto") → verifica si termina con algo.

"subcadena" in cadena → verifica si existe una subcadena dentro de la cadena.

In [7]:

# Verificar contenido
print("Python" in texto)       # True
print(texto.startswith("Py"))  # False
print(texto.endswith(" "))     # False

True
False
True


### Ejercicio: Manejo de cadenas

1. Declara una cadena con el siguiente texto:
   `"   Bienvenidos a la clase de Python   "`
2. Realiza las siguientes operaciones:
   - Elimina los espacios en blanco al inicio y al final.
   - Convierte toda la cadena en **mayúsculas**.
   - Reemplaza la palabra `"Python"` por `"Programación"`.
   - Divide la cadena en palabras y guárdalas en una lista.
   - Une la lista de palabras con guiones (`-`).

3. Muestra los resultados en pantalla.


In [14]:
texto1="   Bienvenidos a la clase de Python   "
texto2=texto1.strip()
print(texto2)
texto2=texto2.upper()
print(texto2)
texto2=texto2.replace("PYTHON", "Programación")
print(texto2)
list=texto2.split()
print(list)
nuevo = "-".join(list)
print(nuevo)


Bienvenidos a la clase de Python
BIENVENIDOS A LA CLASE DE PYTHON
BIENVENIDOS A LA CLASE DE Programación
['BIENVENIDOS', 'A', 'LA', 'CLASE', 'DE', 'Programación']
BIENVENIDOS-A-LA-CLASE-DE-Programación


### 3.4 Arreglos multidimensionales

En Python, los **arreglos multidimensionales** permiten organizar los datos en más de una dimensión.  
El más común es el **arreglo bidimensional**, que se puede ver como una tabla con filas y columnas.

Se pueden representar de dos maneras:
1. Usando **listas de listas**.
2. Usando librerías como **NumPy**, que permiten un manejo más eficiente de matrices.

---

### 3.4.1 Definición de arreglos bidimensionales

Un **arreglo bidimensional** es una colección de elementos organizados en **filas** y **columnas**.

Ejemplo conceptual:  


In [5]:
#Matriz 2x3
A=[ [1, 2, 3],
[4, 5, 6] ]
A

[[1, 2, 3], [4, 5, 6]]

In [3]:
import numpy as np

B=np.array([ [1, 2, 3],
            [4, 5, 6] ])
B

array([[1, 2, 3],
       [4, 5, 6]])


---

### 3.4.2 Operaciones básicas con arreglos bidimensionales

Algunas operaciones comunes con matrices son:
- **Acceder a un elemento**: `matriz[fila][columna]`
- **Recorrer toda la matriz** con ciclos `for`
- **Suma de elementos**
- **Transposición** (intercambiar filas por columnas)



In [ ]:
#Acceder 
A[1][1]

5

In [30]:

c=np.array([[7,2,-1,3],[5,2,0,2],[-5,4,2,-1],[3,1,4,2]])
c=c.astype(float)
c

array([[ 7.,  2., -1.,  3.],
       [ 5.,  2.,  0.,  2.],
       [-5.,  4.,  2., -1.],
       [ 3.,  1.,  4.,  2.]])

In [ ]:
#ubicar elemento
c[1,0]

np.int64(5)

In [ ]:
#Obtener toda la fila 2
c[1,:]

array([5, 2, 0, 2])

In [27]:
c=c.astype(float)
c

array([[ 7.,  2., -1.,  3.],
       [ 5.,  2.,  0.,  2.],
       [-5.,  4.,  2., -1.],
       [ 3.,  1.,  4.,  2.]])

In [31]:
c[0,:]=(1/7)*c[0,:]
c

array([[ 1.        ,  0.28571429, -0.14285714,  0.42857143],
       [ 5.        ,  2.        ,  0.        ,  2.        ],
       [-5.        ,  4.        ,  2.        , -1.        ],
       [ 3.        ,  1.        ,  4.        ,  2.        ]])

In [32]:
c[1,:]=c[1,:]-c[1,0]*c[0,:]
c[2,:]=c[2,:]-c[2,0]*c[0,:]
c[3,:]=c[3,:]-c[3,0]*c[0,:]
c

array([[ 1.        ,  0.28571429, -0.14285714,  0.42857143],
       [ 0.        ,  0.57142857,  0.71428571, -0.14285714],
       [ 0.        ,  5.42857143,  1.28571429,  1.14285714],
       [ 0.        ,  0.14285714,  4.42857143,  0.71428571]])

In [33]:
c[1,:]=c[1,:]/c[1,1]
c

array([[ 1.        ,  0.28571429, -0.14285714,  0.42857143],
       [ 0.        ,  1.        ,  1.25      , -0.25      ],
       [ 0.        ,  5.42857143,  1.28571429,  1.14285714],
       [ 0.        ,  0.14285714,  4.42857143,  0.71428571]])

In [34]:
d=np.array([[3,4,5],[-5,2,8],[5,3,2]])
d

array([[ 3,  4,  5],
       [-5,  2,  8],
       [ 5,  3,  2]])

In [35]:
e=np.array([[4,2,7],[-2,6,7],[9,2,3]])
e

array([[ 4,  2,  7],
       [-2,  6,  7],
       [ 9,  2,  3]])

In [39]:
print(f"el determinante de la matriz d es {round(np.linalg.det(d))}")

el determinante de la matriz d es 15


In [40]:
print(f"el determinante de la matriz e es {round(np.linalg.det(e))}")

el determinante de la matriz e es -252


In [ ]:
#Multiplicación de matrices
d@e

array([[49, 40, 64],
       [48, 18,  3],
       [32, 32, 62]])

In [ ]:
#inversa
np.linalg.inv(e)

array([[-0.01587302, -0.03174603,  0.11111111],
       [-0.27380952,  0.20238095,  0.16666667],
       [ 0.23015873, -0.03968254, -0.11111111]])

In [46]:
e@np.linalg.inv(e)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 2.77555756e-17, 1.00000000e+00]])

---

### 3.4.3 Declaración e inicialización de arreglos multidimensionales

En Python podemos declarar e inicializar arreglos multidimensionales de varias formas:
- Directamente con listas anidadas
- Usando comprensión de listas
- Con librerías como **NumPy**, que facilitan operaciones matemáticas

---


3.4.1 Definición de arreglos bidimensionales

In [ ]:
# Definición de un arreglo bidimensional (matriz 2x3)
matriz = [
    [1, 2, 3],
    [4, 5, 6]
]

print("Matriz:")
for fila in matriz:
    print(fila)

# Acceder al elemento de la fila 1, columna 2
print("Elemento en [1][2]:", matriz[1][2])  # 6


3.4.2 Operaciones básicas con arreglos bidimensionales

In [ ]:
# Matriz de ejemplo
matriz = [
    [1, 2, 3],
    [4, 5, 6]
]

# Recorrer la matriz con índices
print("Recorriendo con índices:")
for i in range(len(matriz)):
    for j in range(len(matriz[0])):
        print(f"Elemento [{i}][{j}] = {matriz[i][j]}")

# Suma de todos los elementos
suma = 0
for fila in matriz:
    for valor in fila:
        suma += valor
print("Suma de los elementos:", suma)

# Transposición (convertir filas en columnas)
transpuesta = [[matriz[j][i] for j in range(len(matriz))] for i in range(len(matriz[0]))]
print("Matriz transpuesta:", transpuesta)


### 3.4.3 Declaración e inicialización de arreglos multidimensionales

En Python, los **arreglos multidimensionales** se pueden crear de diferentes maneras.  
El más común es el **arreglo bidimensional (matriz)**, pero también se pueden declarar arreglos con más dimensiones.

Existen tres formas principales:

---

#### 1. Usando listas anidadas
Las listas de listas permiten declarar arreglos multidimensionales de manera sencilla.
```python
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


2. Usando comprensión de listas

Sirve para crear arreglos inicializados con valores predeterminados, como ceros o un mismo número.

In [ ]:
# Matriz de 3x3 con ceros
matriz_ceros = [[0 for _ in range(3)] for _ in range(3)]


3. Usando la librería NumPy

La librería NumPy es muy útil para trabajar con arreglos multidimensionales, ya que incluye operaciones matemáticas y funciones optimizadas.

In [47]:
import numpy as np

# Matriz 3x3 con valores definidos
matriz_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Matriz de ceros
matriz_ceros = np.zeros((3, 3))

# Matriz de unos
matriz_unos = np.ones((2, 4))

# Matriz identidad (diagonal principal en 1)
identidad = np.eye(3)

# Matriz con valores aleatorios
matriz_random = np.random.randint(1, 10, size=(3, 3))


4. Arreglos tridimensionales o más

Python también permite trabajar con más de dos dimensiones (3D, 4D, etc.), lo cual es útil en aplicaciones como procesamiento de imágenes o ciencia de datos.

In [ ]:
cubo = [
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]


In [4]:
import numpy as np
tensor = np.random.randint(1, 10, size=(2, 3, 4))  # Arreglo 3D
tensor


array([[[4, 2, 7, 9],
        [2, 3, 5, 6],
        [3, 8, 2, 4]],

       [[7, 6, 7, 6],
        [7, 8, 9, 7],
        [1, 1, 6, 8]]], dtype=int32)

In [ ]:

# 1. Declaración manual con listas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Matriz declarada manualmente:", matriz)

# 2. Declaración con comprensión de listas (matriz de 4x4 con ceros)
matriz_ceros = [[0 for _ in range(4)] for _ in range(4)]
print("Matriz de ceros (4x4):", matriz_ceros)

# 3. Declaración con NumPy
import numpy as np

matriz_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz NumPy:\n", matriz_numpy)

matriz_unos = np.ones((2, 3))
print("Matriz de unos:\n", matriz_unos)

identidad = np.eye(4)
print("Matriz identidad 4x4:\n", identidad)

matriz_random = np.random.randint(1, 10, size=(3, 3))
print("Matriz aleatoria 3x3:\n", matriz_random)

# 4. Arreglo tridimensional
tensor = np.random.randint(1, 10, size=(2, 2, 3))
print("Arreglo tridimensional (2x2x3):\n", tensor)


# Método de Gauss-Jordan

El **método de Gauss-Jordan** es una técnica para resolver sistemas de ecuaciones lineales.  
Se basa en transformar la **matriz aumentada** del sistema en una **matriz identidad**, mediante operaciones elementales por renglones:

1. **Intercambiar renglones**: cambiar la posición de dos filas.  
2. **Multiplicar un renglón por un escalar distinto de 0**.  
3. **Sumar o restar un múltiplo de un renglón a otro**.  

Cuando la matriz se transforma en la **matriz identidad**, las soluciones del sistema aparecen en la última columna de la matriz aumentada.  

---

## Ejemplo teórico

Resolver el sistema de ecuaciones:


2x + y - z = 8


-3x - y + 2z = -11



-2x + y + 2z = -3


---

### 1. Escribimos la matriz aumentada:


\begin{bmatrix}
2 & 1 & -1 & | & 8 \\
-3 & -1 & 2 & | & -11 \\
-2 & 1 & 2 & | & -3
\end{bmatrix}


---

### 2. Aplicamos operaciones por renglones hasta obtener la matriz identidad:


\begin{bmatrix}
1 & 0 & 0 & | & 2 \\
0 & 1 & 0 & | & 3 \\
0 & 0 & 1 & | & -1
\end{bmatrix}


---

### 3. La solución es:


x = 2,  y = 3,  z = -1


---


In [ ]:
import numpy as np

def gauss_jordan(a, b):
    # Creamos la matriz aumentada
    n = len(b)
    M = np.hstack([a.astype(float), b.reshape(-1,1)])
    
    for i in range(n):
        # Hacemos que el pivote sea 1
        M[i] = M[i] / M[i, i]
        
        # Hacemos ceros en la columna i, excepto en la diagonal
        for j in range(n):
            if i != j:
                M[j] = M[j] - M[j, i] * M[i]
    
    # La última columna es la solución
    return M[:, -1]

In [49]:
# Ejemplo
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]], dtype=float)

B = np.array([8, -11, -3], dtype=float)

solucion = gauss_jordan(A, B)
print("Solución del sistema:")
print(f"x = {solucion[0]}, y = {solucion[1]}, z = {solucion[2]}")

Solución del sistema:
x = 2.0, y = 3.0, z = -1.0
